package org.golfworld.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.golfworld.db.domain.BallPackProduct;
import org.golfworld.db.domain.BallPackProductExample;

public interface BallPackProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    long countByExample(BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int deleteByExample(BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int insert(BallPackProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int insertSelective(BallPackProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    BallPackProduct selectOneByExample(BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    BallPackProduct selectOneByExampleSelective(@Param("example") BallPackProductExample example, @Param("selective") BallPackProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    List<BallPackProduct> selectByExampleSelective(@Param("example") BallPackProductExample example, @Param("selective") BallPackProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    List<BallPackProduct> selectByExample(BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    BallPackProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BallPackProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    BallPackProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    BallPackProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BallPackProduct record, @Param("example") BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BallPackProduct record, @Param("example") BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BallPackProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BallPackProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BallPackProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}