package org.golfworld.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.golfworld.db.domain.BallPack;
import org.golfworld.db.domain.BallPackExample;

public interface BallPackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    long countByExample(BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int deleteByExample(BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int insert(BallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */

    int insertSelective(BallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    BallPack selectOneByExample(BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    BallPack selectOneByExampleSelective(@Param("example") BallPackExample example, @Param("selective") BallPack.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    List<BallPack> selectByExampleSelective(@Param("example") BallPackExample example, @Param("selective") BallPack.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    List<BallPack> selectByExample(BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    BallPack selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BallPack.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    BallPack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    BallPack selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BallPack record, @Param("example") BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BallPack record, @Param("example") BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ball_pack
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}