package org.golfworld.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.golfworld.db.domain.CouponUser;
import org.golfworld.db.domain.CouponUserExample;

public interface CouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int insert(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    CouponUser selectOneByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    CouponUser selectOneByExampleSelective(@Param("example") CouponUserExample example, @Param("selective") CouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    List<CouponUser> selectByExampleSelective(@Param("example") CouponUserExample example, @Param("selective") CouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    List<CouponUser> selectByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    CouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    CouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    CouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CouponUser record, @Param("example") CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CouponUser record, @Param("example") CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}