package org.golfworld.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.golfworld.db.domain.GoodsProduct;
import org.golfworld.db.domain.GoodsProductExample;

public interface GoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    long countByExample(GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int insert(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    GoodsProduct selectOneByExample(GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    GoodsProduct selectOneByExampleSelective(@Param("example") GoodsProductExample example, @Param("selective") GoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    List<GoodsProduct> selectByExampleSelective(@Param("example") GoodsProductExample example, @Param("selective") GoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    List<GoodsProduct> selectByExample(GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    GoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    GoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    GoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsProduct record, @Param("example") GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsProduct record, @Param("example") GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);


    int addStock(@Param("id") Integer id, @Param("num") Short num);

    int reduceStock(@Param("id") Integer id, @Param("num") Short num);
}