package org.golfworld.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.golfworld.db.domain.ProductAttribute;
import org.golfworld.db.domain.ProductAttributeExample;

public interface ProductAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    long countByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int insert(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttribute selectOneByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttribute selectOneByExampleSelective(@Param("example") ProductAttributeExample example, @Param("selective") ProductAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    List<ProductAttribute> selectByExampleSelective(@Param("example") ProductAttributeExample example, @Param("selective") ProductAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    List<ProductAttribute> selectByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ProductAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductAttribute record, @Param("example") ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductAttribute record, @Param("example") ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}